version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    container_name: twsl-db 
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - twsl-dev_db:/var/lib/postgresql/data

volumes:
  twsl-dev_db:
